## The switching-gene:
    1. Only on training set
    2. The genes with sequence length between 200-5000 
    3. exculde the cell line H1.hESC
    4. Two cyto-nuclear class thresholds were tested:
        aa. 0. CN-RCI >= 0 is cyto, otherwise nuclear
    5. The switching genes: 
        aa. both the numbers of cell lines for cyto and nucleus are greater than or equal to 1
        bb. the absolute value of difference between cyto and nucleus abs(cyto-nucleus) <= 1

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import openpyxl
from pandas import ExcelWriter

In [2]:
def isswitch(row):
    if abs(row["Cyto-Nuclear"]) <= 1 and row["Nucleus"]>1 and row["Cyto"]>1:
        return 1
    else:
        return 0

In [3]:
path_input = "../data/"
path_output = "../results/switching_genes/"
os.makedirs(path_output, exist_ok=True)

In [11]:
wb = openpyxl.Workbook()
output_file = path_input + "Supplementary_Table2_185_switching_genes.xlsx"
wb.save(output_file)
writer = ExcelWriter(output_file, engine='openpyxl',mode='a')

In [5]:
_df = pd.read_csv(path_input+"Supplementary_Table3_lncRNA_train_seq_with_RCI_longest_transcripts.csv",index_col=0)

In [6]:
dff = _df.iloc[:,-19:].drop(["biotype","length","sequence","H1.hESC"],axis=1)

dff

,gene_id,A549,HeLa.S3,HepG2,HT1080,HUVEC,MCF.7,NCI.H460,NHEK,SK.MEL.5,SK.N.DZ,SK.N.SH,GM12878,K562,IMR.90
0,ENSG00000254154,-0.571906,NaN,-3.245620,NaN,-3.50057,-1.848000,NaN,-2.42403,NaN,NaN,-2.8679,-3.310790,NaN,-3.72094
1,ENSG00000261026,NaN,NaN,NaN,NaN,-5.52356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ENSG00000230894,0.584962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ENSG00000227733,NaN,NaN,NaN,NaN,NaN,-6.179910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ENSG00000180539,NaN,NaN,NaN,NaN,NaN,-4.736970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4602,ENSG00000273107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4603,ENSG00000269978,NaN,NaN,NaN,NaN,NaN,-6.089180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4604,ENSG00000276232,NaN,-1.78159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4605,ENSG00000268189,0.000000,NaN,-0.584962,-0.247928,NaN,-0.169925,NaN,NaN,NaN,NaN,NaN,-0.192645,NaN,NaN
4606,ENSG00000227726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
new_dff_ = dff.copy()
new_dff_ = new_dff_.set_index("gene_id")
new_dff_ = new_dff_.dropna(how="all")

In [14]:
new_dff_

,A549,HeLa.S3,HepG2,HT1080,HUVEC,MCF.7,NCI.H460,NHEK,SK.MEL.5,SK.N.DZ,SK.N.SH,GM12878,K562,IMR.90
gene_id,,,,,,,,,,,,,,
ENSG00000254154,-0.571906,NaN,-3.245620,NaN,-3.50057,-1.848000,NaN,-2.42403,NaN,NaN,-2.8679,-3.310790,NaN,-3.72094
ENSG00000261026,NaN,NaN,NaN,NaN,-5.52356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000230894,0.584962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000227733,NaN,NaN,NaN,NaN,NaN,-6.179910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000180539,NaN,NaN,NaN,NaN,NaN,-4.736970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000234160,NaN,NaN,NaN,NaN,NaN,-2.992770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000273568,-0.312830,NaN,-2.027120,NaN,NaN,-0.459976,NaN,NaN,NaN,NaN,NaN,-0.044123,NaN,NaN
ENSG00000269978,NaN,NaN,NaN,NaN,NaN,-6.089180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000276232,NaN,-1.78159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000268189,0.000000,NaN,-0.584962,-0.247928,NaN,-0.169925,NaN,NaN,NaN,NaN,NaN,-0.192645,NaN,NaN

In [15]:
new_dff = new_dff_.copy()

# threshold 0

In [16]:
new_dff.iloc[:,0:14][new_dff.iloc[:,0:14] >= 0] = 1    # Set values >= 0 to 1
new_dff.iloc[:,0:14][new_dff.iloc[:,0:14] < 0] = 0    # Set values < 0 to 0

new_dff.iloc[:,0:14][new_dff.iloc[:,0:14].isna()] = np.nan

new_dff["Total_cell_line"] = new_dff.iloc[:,0:14].notnull().sum(axis=1)
# Add a column to store the number of columns with each value

new_dff["Nucleus"] = (new_dff.iloc[:,0:14] == 0).sum(axis=1)
new_dff["Cyto"] = (new_dff.iloc[:,0:14] == 1).sum(axis=1)
new_dff["Cyto-Nuclear"] = new_dff["Cyto"] - new_dff["Nucleus"]
new_dff["Is_switching_gene"] = new_dff.apply(lambda row:isswitch(row),axis=1)
new_dff = new_dff.reset_index()
new_dff_ = new_dff_.reset_index()
dff_switch0 = new_dff_.merge(new_dff,on="gene_id",how="left").sort_values(["Is_switching_gene"],ascending=False).reset_index(drop=True)
dff_switch0.to_excel(writer,sheet_name="switch_gene_threshhold_0")
writer.close()

C:\Users\weiju\AppData\Local\Temp\ipykernel_52004\1199447388.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  new_dff.iloc[:,0:14][new_dff.iloc[:,0:14] >= 0] = 1    # Set values >= 0 to 1
C:\Users\weiju\AppData\Local\Temp\ipykernel_52004\1199447388.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  new_dff.iloc[:,0:14][new_dff.iloc[:,0:14] < 0] = 0    # Set values < 0 to 0
C:\Users\weiju\AppData\Local\Temp\ipykernel_52004\1199447388.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  new_dff.iloc[:,0:14][new_dff.iloc[:,0:14].isna()] = np.nan

In [ ]:
dff_switch0.Is_switching_gene.value_counts()