https://www.sciencedirect.com/science/article/pii/S0092867419305550#app2

Many RNAs are ‘‘orphans,’’never previously linked to the compartment to which APEX-seq assigns them. For instance, our APEX-seq atlas (Figure 2F) newly assigns 324 RNAs to the nucleolus, 114 RNAs to the lamina, and 111 RNAs to the OMM (Table S3)
9 locations:Nucleus; Nuclear lamina; Nucleolus; Nuclear pore; ;Cytosol; Mitochondrial matrix ;Endoplasmic reticulum membrane (ER membrane); ER lumen; Outer mitochondrial membrane (OMM)

Nuclear pore — can be excluded or treated as ambiguous, as it's a gateway between the nucleus and cytoplasm.
exclude mitochondrial compartments if your focus is only on classic RNA cytoplasmic trafficking.

In this notebook, using threshold logFC 0.75 to assign location

<font size = 6, color="blue"> Nucleus: 'Nucleus_log2FC', 'Nucleolus_log2FC', 'Lamina_log2FC'</font>


<font size = 6, color="blue"> Cytoplasm:'Cytosol_log2FC', 'ERM_log2FC', 'OMM_log2FC', 'ER_Lumen_log2FC'</font>

<font size = 6, color="red"> Nuclear pore — can be excluded or treated as ambiguous, as it's a gateway between the nucleus and cytoplasm</font>

<font size = 6, color="blue"> remove muti_position</font>

In [1]:
import pandas as pd
import os
from collections import Counter

In [2]:
cur_dir = os.getcwd()
os.listdir(cur_dir)

['.ipynb_checkpoints',
 '1. GENCODE_lncATLAS_ProcessGENCODE.ipynb',
 '2.GENCODE_lncATLAS_ProcessLncATLAS.ipynb',
 '3_GENCODE_lncATLAS_combine_seq_with_CNRCI.ipynb',
 '4. APEX-Seq_data from paper_logFC_075.ipynb']

In [5]:
path_input = "../../data/APEX-Seq/"

In [16]:
output_path = path_input
os.makedirs(output_path, exist_ok=True)

In [6]:
xl = pd.ExcelFile(path_input+"1-s2.0-S0092867419305550-mmc3.xlsx")
xl.sheet_names

['Column definitions',
 'Gene lists and orphans',
 'ERM and OMM cytosol normalized']

In [7]:
df_all = xl.parse("Gene lists and orphans")
df_all

,Ensembl_Gene,Common_Gene,Source,Nucleus_log2FC,Nucleolus_log2FC,Lamina_log2FC,Nuclear_Pore_log2FC,Cytosol_log2FC,ERM_log2FC,OMM_log2FC,ER_Lumen_log2FC,Nucleus_Orphan,Nucleolus_Orphan,Lamina_Orphan,Nuclear_pore_Orphan,Cytosol_Orphan,ERM_Orphan,OMM_Orphan,Nucleus_Deorphaned,Cytosol_Deorphaned
0,ENSG00000001084,GCLC,Atlas_Analysis,0.846218,0.552665,0.792827,-0.769937,0.015406,0.366243,0.053642,-0.193563,1,0,0,0,0,0,0,0,0
1,ENSG00000001167,NFYA,Atlas_Analysis,0.317604,0.760535,0.056036,-0.327346,0.366742,0.366740,0.161656,-0.022024,0,0,0,0,0,0,0,0,0
2,ENSG00000001461,NIPAL3,Atlas_Analysis,-0.388237,0.348581,0.411313,-0.087371,0.458414,1.529406,1.335787,0.038575,0,0,0,0,0,0,0,0,0
3,ENSG00000001561,ENPP4,Atlas_Analysis,0.167409,-0.870507,0.558327,-0.631704,-0.796273,1.259571,1.173992,-0.284607,0,0,0,0,0,0,0,0,0
4,ENSG00000001617,SEMA3F,Atlas_Analysis,0.331924,1.144999,0.065756,0.275560,0.037641,1.028073,1.246572,0.493677,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3330,ENSG00000279453,NaN,ERM_Analysis,-0.268188,0.576316,0.532708,-0.873112,0.671938,3.170824,2.021101,0.124042,0,0,0,0,0,1,0,0,0
3331,ENSG00000279948,NaN,ERM_Analysis,1.695306,-2.850918,-1.743358,-2.944385,2.167194,6.573358,-3.149922,1.534635,0,0,0,0,0,1,0,0,0
3332,ENSG00000280322,AL035425.4,Atlas_Analysis,3.916195,2.421028,4.344689,1.309427,-1.116130,0.151599,-0.186812,0.499380,0,0,0,0,0,0,0,0,0
3333,ENSG00000281649,EBLN3P,Atlas_Analysis,0.484353,0.934240,0.927135,-0.139260,0.065630,0.725203,0.206560,-0.185605,0,0,0,0,0,0,0,0,0
3334,ENSG00000283041,NaN,OMM_Analysis,-1.000954,-0.884040,-1.110270,-0.225917,-0.336450,-0.944854,0.638877,-0.169685,0,0,0,0,0,0,1,0,0

In [8]:
# List of log2FC columns
log2fc_columns = [
    'Nucleus_log2FC', 'Nucleolus_log2FC', 'Lamina_log2FC', 'Nuclear_Pore_log2FC',
    'Cytosol_log2FC', 'ERM_log2FC', 'OMM_log2FC', 'ER_Lumen_log2FC']

# Using threshold >=0.75 class 1, otherwise 0
log2fc_binary_df = (df_all[log2fc_columns] >= 0.75).astype(int)
log2fc_binary_df.columns = [col.replace('_log2FC', '_bin_075') for col in log2fc_binary_df.columns]

df_expanded = pd.concat([df_all, log2fc_binary_df], axis=1)

In [6]:
log2fc_binary_df.columns

Index(['Nucleus_bin_075', 'Nucleolus_bin_075', 'Lamina_bin_075',
       'Nuclear_Pore_bin_075', 'Cytosol_bin_075', 'ERM_bin_075', 'OMM_bin_075',
       'ER_Lumen_bin_075'],
      dtype='object')

In [12]:
nuclear = ['Nucleus_bin_075', 'Nucleolus_bin_075', 'Lamina_bin_075']
cytoplasmic = ['Cytosol_bin_075', 'ERM_bin_075', 'OMM_bin_075','ER_Lumen_bin_075']
boundry = ['Nuclear_Pore_bin_075']

In [9]:
def assign_class(row):
    if (row[nuclear].sum() >= 1 ) and (row[cytoplasmic].sum()==0) and (row[boundry].sum()==0):
        return 0
    elif (row[nuclear].sum() == 0 ) and (row[cytoplasmic].sum()>=1) and (row[boundry].sum()==0):
        return 1
#     elif  (row[nuclear].sum() == 0 ) and (row[cytoplasmic].sum()==0) and (row[boundry].sum()==1):
#         return 3
    else:
        return 2

In [10]:
df_expanded.columns

Index(['Ensembl_Gene', 'Common_Gene', 'Source', 'Nucleus_log2FC',
       'Nucleolus_log2FC', 'Lamina_log2FC', 'Nuclear_Pore_log2FC',
       'Cytosol_log2FC', 'ERM_log2FC', 'OMM_log2FC', 'ER_Lumen_log2FC',
       'Nucleus_Orphan', 'Nucleolus_Orphan', 'Lamina_Orphan',
       'Nuclear_pore_Orphan', 'Cytosol_Orphan', 'ERM_Orphan', 'OMM_Orphan',
       'Nucleus_Deorphaned', 'Cytosol_Deorphaned', 'Nucleus_bin_075',
       'Nucleolus_bin_075', 'Lamina_bin_075', 'Nuclear_Pore_bin_075',
       'Cytosol_bin_075', 'ERM_bin_075', 'OMM_bin_075', 'ER_Lumen_bin_075'],
      dtype='object')

In [13]:
df_expanded["Class"] = df_expanded.apply(lambda row:assign_class(row),axis=1)

In [14]:
df_expanded["Class"].value_counts()

Class
1    1345
0    1005
2     985
Name: count, dtype: int64

In [16]:
apex_genes = df_all.Ensembl_Gene

In [17]:
df_expanded.to_excel(output_path+"expended_table_with_class_logFC075.xlsx")

In [18]:
df_valid = df_expanded[df_expanded["Class"] != 2].reset_index(drop=True)
df_valid

,Ensembl_Gene,Common_Gene,Source,Nucleus_log2FC,Nucleolus_log2FC,Lamina_log2FC,Nuclear_Pore_log2FC,Cytosol_log2FC,ERM_log2FC,OMM_log2FC,...,Cytosol_Deorphaned,Nucleus_bin_075,Nucleolus_bin_075,Lamina_bin_075,Nuclear_Pore_bin_075,Cytosol_bin_075,ERM_bin_075,OMM_bin_075,ER_Lumen_bin_075,Class
0,ENSG00000001084,GCLC,Atlas_Analysis,0.846218,0.552665,0.792827,-0.769937,0.015406,0.366243,0.053642,...,0,1,0,1,0,0,0,0,0,0
1,ENSG00000001167,NFYA,Atlas_Analysis,0.317604,0.760535,0.056036,-0.327346,0.366742,0.366740,0.161656,...,0,0,1,0,0,0,0,0,0,0
2,ENSG00000001461,NIPAL3,Atlas_Analysis,-0.388237,0.348581,0.411313,-0.087371,0.458414,1.529406,1.335787,...,0,0,0,0,0,0,1,1,0,1
3,ENSG00000001561,ENPP4,Atlas_Analysis,0.167409,-0.870507,0.558327,-0.631704,-0.796273,1.259571,1.173992,...,0,0,0,0,0,0,1,1,0,1
4,ENSG00000002586,CD99,Atlas_Analysis,-0.894382,-1.070904,-0.811157,0.098431,-0.399164,-0.013226,0.887834,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2345,ENSG00000278540,ACACA,Atlas_Analysis,-0.172746,0.269883,0.021795,-0.100115,0.313589,1.477630,1.161022,...,0,0,0,0,0,0,1,1,0,1
2346,ENSG00000278730,AC005332.6,Atlas_Analysis,0.240529,-0.147555,0.364251,0.124210,0.442321,0.551813,0.936570,...,0,0,0,0,0,0,0,1,0,1
2347,ENSG00000279088,RP11-574K11,Atlas_Analysis,0.983359,1.034940,1.189880,0.512785,-1.625087,-4.537484,-0.558565,...,0,1,1,1,0,0,0,0,0,0
2348,ENSG00000279453,NaN,ERM_Analysis,-0.268188,0.576316,0.532708,-0.873112,0.671938,3.170824,2.021101,...,0,0,0,0,0,0,1,1,0,1
2349,ENSG00000281649,EBLN3P,Atlas_Analysis,0.484353,0.934240,0.927135,-0.139260,0.065630,0.725203,0.206560,...,0,0,1,1,0,0,0,0,0,0

In [19]:
_df_valid = df_valid[["Ensembl_Gene","Class"]]
_df_valid.columns = ["gene_id","Class"]
_df_valid

              gene_id  Class
0     ENSG00000001084      0
1     ENSG00000001167      0
2     ENSG00000001461      1
3     ENSG00000001561      1
4     ENSG00000002586      1
...               ...    ...
2345  ENSG00000278540      1
2346  ENSG00000278730      1
2347  ENSG00000279088      0
2348  ENSG00000279453      1
2349  ENSG00000281649      0

[2350 rows x 2 columns]

In [20]:
_df_coding_seq = pd.read_csv("../../data/GenCode/gencode.v42.pc_transcripts.csv")
_df_noncoding_seq = pd.read_csv("../../data/GenCode/gencode.v42.lncRNA_transcripts.csv")

In [21]:
df_coding_seq = _df_coding_seq.sort_values(by="length", ascending=False)
df_coding_seq_200_5000 = df_coding_seq[df_coding_seq.length.between(200, 5000,inclusive="both")]
df_coding_seq = df_coding_seq_200_5000.drop_duplicates("gene_id")

df_noncoding_seq = _df_noncoding_seq.sort_values(by="length", ascending=False)
df_noncoding_seq_200_5000 = df_noncoding_seq[df_noncoding_seq.length.between(200, 5000,inclusive="both")]
df_noncoding_seq = df_noncoding_seq_200_5000.drop_duplicates("gene_id")

In [24]:
pd.merge(df_noncoding_seq,_df_valid,on="gene_id",how="inner").to_csv("../../data/Supplementary Table9_apex_lncRNA_transcripts.csv")

In [26]:
pd.merge(df_coding_seq,_df_valid,on="gene_id",how="inner").to_csv("../../data/Supplementary Table10_apex_mRNA_transcripts.csv")